/* plan-seed.js — the exact 2018 ዓ/ም ዕቅድ from
 * "2018_የንብረት_ክፍል_እቅድ.docx", seeded automatically on first load. */
window.NK_PLAN_SEED = [
  {
    no: 1,
    subUnit: '',
    title: 'ክፍሉን በሰዉ ሀይልና ቁሳቁስ ማደራጀት',
    details: 'ያሉንን አባላት እንዲሰሩ ቅስቀሳ ማድረግ እና ተጨማሪ አባላት ወደ ክፍሉ እንዲገቡ ማድረግ; ላሉት ንብረቶች ማስቀመጫ መስራት',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: 'ጥቅምት',
    executor: 'የክፍሉ ጽ/ቤት',
    budget: '',
    weight: '55%',
    category: 'main',
  },
  {
    no: 2,
    subUnit: '',
    title: 'የ2018 ሂሳብ ማዘጋጀት',
    details: 'ገቢ እና ወጪ በዝርዝር ማስቀመጥ; የተሰራውን ኦዲት አንድ ላይ ከነትርፉ ለሚመለከተው ማሳወቅ',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '',
    timing: 'ነሃሴ',
    executor: 'ሂሳብ ክፍል',
    budget: '',
    weight: '10%',
    category: 'main',
  },
  {
    no: 3,
    subUnit: '',
    title: 'አዳዲስ ወደ ሰ/ት/ቤቱ በስጦታም ሆን በግዢ መልክ የሚመጡ ንብረቶችን ቆጥሮ መረከብ ባጠቃላይ ያለዉን ንብረት በቁጥር መቆጣጠር',
    details: 'አዲስ ንብረቶችን ለሚመለከተዉ ክፍል ማስረከብ; በንብረት ክፍል የሚገኙ ዕቃዎችን ያለደብዳቤ አለማዉጣት ሲመለስ ቆጥሮ መረከብ እና ፎርም ማዘጋጀት; ሁሉንም ንብረቶች መቆጣጠርና መጠበቅ; ኮድ የሚያስፈልገው ንብረት ኮድ ስለተሰጠው ንብረቶችን በዛ መቆጣጠር',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: 'እንደአስፈላጊነቱ',
    executor: 'ንብረትእና ቁጥጥር ክፍል',
    budget: '',
    weight: '55%',
    category: 'main',
  },
  {
    no: 4,
    subUnit: '',
    title: 'ከክፍሉ አመራሮች ወርሃዊ መዋጮ መሰብሰብ',
    details: 'የሚሰበስብ ሰዉ መመደብ; አመራሮች እንዲሰበሰቡ ቅስቀሳ ማድረግ',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: '12 ጊዜ',
    executor: 'የገቢና ወጪ ቁጥጥር',
    budget: '',
    weight: '10%',
    category: 'main',
  },
  {
    no: 5,
    subUnit: '',
    title: 'ከምዕመናን ለእንቁጣጣሽ፣ ለመስቀል እንኳነነን አደረሳችሁ በማለት የሚሰበሰበዉን ገንዘብ መቆጣጠር',
    details: 'ቆጥሮ መረከብ; ባንክ ማስገባት; የገቢ ደረሰኝ ለመዝሙር ክፍል እና ለጽ/ቤት መስጠት',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: '3 ጊዜ',
    executor: 'የገቢና ወጪ ቁጥጥር ክፍል',
    budget: '',
    weight: '33%',
    category: 'main',
  },
  {
    no: 6,
    subUnit: '',
    title: 'በስራ አመራሮች ተወስኖ የሚወጣዉን ገንዘብ',
    details: 'በሰ/ት/ቤት ሰብሳቢ የተፈቀደዉን ደብዳቤ ላይ ፊርማ መኖሩን ማረጋገጥ; ወጪዉ የታሰበለት አላማ ላይ መዋሉን ቆጣጠርና ሂሳብ መወራረድ',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: '',
    executor: 'የገቢና ወጪ ቁጥጥር ክፍል',
    budget: '',
    weight: '10%',
    category: 'main',
  },
  {
    no: 7,
    subUnit: '',
    title: 'የተበላሸና የተሰበሩ ጥገና የሚያስፈልጋቸዉ ንብረቶች እንዲጠገኑ ማድረግ',
    details: 'በበጎ ፈቃደኝነት የሚሰራ አካል ከተገኘ መፈለግ; የተበላሹ መለየት ወጪ መጠየቅ በመከታተል ወደ ሰ/ት/ቤት ካዝና ገቢ ማድረግ',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: 'እንደአስፈላጊነቱ',
    executor: 'ንብረትእና ቁጥጥር',
    budget: '',
    weight: '5%',
    category: 'main',
  },
  {
    no: 8,
    subUnit: '',
    title: 'በሰ/ት/ቤቱ ክፍሎች በየትኛዉም መንገድ የሚሰበሰቡ ገንዘቦችን (ገቢዎችን) መቆጣጠር',
    details: 'የገንዘቡን ግለሰብ እጅ ላይ እንዳይቆይ ወደ ባንክ ገቢ ማድረግ',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: 'ከመስከረም እስከ ነሃሴ',
    executor: 'ገቢና ወጪ ቁጥጥር ክፍል',
    budget: '',
    weight: '10%',
    category: 'main',
  },
  {
    no: 9,
    subUnit: '',
    title: 'ከልማት ክፍል የሚገኘዉን ገንዘብ በወቅቱ መረከብ',
    details: 'ሂሳብ ማወራረድ; ክፍሉን መከታተል',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: 'ከመስከረም እስከ ነሐሴ',
    executor: 'የልማት ቁጥጥር ክፍል',
    budget: '',
    weight: '5%',
    category: 'main',
  },
  {
    no: 10,
    subUnit: '',
    title: 'የሰ/ት/ቤቱን ንብረት ማሟላት',
    details: 'ዋጋ ማጣራት; ለትልልቅ ድርጅቶች ደብዳቤ ማስገባት',
    outcome: 'አስፈላጊ ንብረቶችን ማሟላትን',
    indicator: 'በቁጥር',
    target: '1 ጊዜ',
    timing: 'ታህሳስ እና ጥር',
    executor: 'የክፍሉ ተጠሪ ከጽ/ቤት ጋር በጋራ በመሆን',
    budget: '',
    weight: '20%',
    category: 'main',
  },
  {
    no: 11,
    subUnit: '',
    title: 'የሶስት ወር ሪፖርት ማድረግ',
    details: 'ከንዑስ ክፍላት ሪፖርት መሰብሰብ',
    outcome: 'በቃል እና በጽሁፍ',
    indicator: 'በቁጥር',
    target: '4ጊዜ',
    timing: 'ህዳር የካቲት ግንቦት ነሐሴ',
    executor: 'የክፍሉ ጽ/ቤት',
    budget: '',
    weight: '3%',
    category: 'main',
  },
  {
    no: 12,
    subUnit: '',
    title: 'የክፍሉ አባላት መሰብሰብ',
    details: 'በወር 1 ጊዜ',
    outcome: '',
    indicator: 'በመቶኛ',
    target: '100%',
    timing: 'ከመስከረም እስከ ነሐሴ',
    executor: 'የክፍሉ ጽ/ቤት',
    budget: '',
    weight: '2%',
    category: 'main',
  },
  {
    no: 13,
    subUnit: '',
    title: 'ንብረት መቁጠር',
    details: 'በአመት ሁለት ጊዜ',
    outcome: '',
    indicator: 'በቁጥር',
    target: '2ጊዜ',
    timing: 'የካቲት ና ነሐሴ',
    executor: 'ንብረት እና ቁጥጥር ክፍል',
    budget: '',
    weight: '5%',
    category: 'main',
  },
  {
    no: 14,
    subUnit: '',
    title: 'የ2019 ዕቅድ ማቀድ',
    details: 'ከንዑስ ክፍላት ዕቅድ መሰብሰብ',
    outcome: 'በጽሁፍ',
    indicator: 'በቁጥር',
    target: '1ጊዜ',
    timing: 'ነሃሴ',
    executor: 'የክፍሉ ጽ/ቤት',
    budget: '',
    weight: '2%',
    category: 'main',
  },
];
